# Generated by Django 4.2.15 on 2025-03-03 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanapp', '0002_remove_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_date'),
        ),
        migrations.AddField(
            model_name='loan',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=255),
        ),
    ]
