# Generated by Django 4.2.15 on 2025-03-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_groups',
        ),
    ]
